plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - 'tasks/**/*.rake'
    - 'features/**/views/**/*.rb'
    - 'lib/patterns/layout.rb'
    - 'lib/patterns/phlex_components/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'features/**/views/**/*.rb'
    - 'lib/patterns/layout.rb'
    - 'lib/patterns/phlex_components/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'features/**/views/**/*.rb'
    - 'lib/patterns/layout.rb'
    - 'lib/patterns/phlex_components/**/*.rb'

Metrics/ParameterLists:
  Exclude:
    - 'features/**/views/**/*.rb'
    - 'lib/patterns/phlex_components/**/*.rb'
