plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - 'tasks/**/*.rake'
